# Generated by Django 4.2.7 on 2025-09-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='image',
            name='unique_image_per_set',
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('image_set', 'image_type')},
        ),
    ]
