# Generated by Django 5.2.6 on 2025-09-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_image_unique_image_per_set_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageset',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(choices=[('input', 'Input'), ('dress', 'Dress'), ('final', 'Final')], max_length=10),
        ),
    ]
